"""Adicionar índices e implementar validações

Revision ID: 87588d1e6fcd
Revises: 
Create Date: 2025-04-03 21:59:01.137424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87588d1e6fcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_servicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendamento_servicos_agendamento_id'), ['agendamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamento_servicos_servico_id'), ['servico_id'], unique=False)

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendamentos_barbeiro_id'), ['barbeiro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_status'), ['status'], unique=False)

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('valor_total', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('data_hora', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.alter_column('agendamento_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_atendimentos_clientes', 'clientes', ['cliente_id'], ['id'])
        batch_op.drop_column('data_hora_inicio')

    with op.batch_alter_table('barbeiros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barbeiros_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_nome'), ['nome'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_nome'))

    with op.batch_alter_table('barbeiros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barbeiros_usuario_id'))

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora_inicio', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint('fk_atendimentos_clientes', type_='foreignkey')
        batch_op.alter_column('agendamento_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('observacoes')
        batch_op.drop_column('status')
        batch_op.drop_column('data_hora')
        batch_op.drop_column('valor_total')
        batch_op.drop_column('cliente_id')

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamentos_status'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_barbeiro_id'))

    with op.batch_alter_table('agendamento_servicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamento_servicos_servico_id'))
        batch_op.drop_index(batch_op.f('ix_agendamento_servicos_agendamento_id'))

    # ### end Alembic commands ###
